# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
#  - osx

julia:
  - 0.5
  - nightly

notifications:
  email:
    recipients:
      - e.zander@tu-bs.de
      - martin.eigel@wias-berlin.de

branch:
  - master
  - testing
#sudo: required
#service:
#  - docker

before_install:
  # Install FEniCS (but don't do an 'apt-get upgrade' as this will timeout the process)
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - sudo add-apt-repository ppa:fenics-packages/fenics -y
  - sudo apt-get update -q
  - sudo apt-get install fenics -y
  #- curl -s https://get.fenicsproject.org | bash
  #-

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("FEniCS"); Pkg.test("FEniCS"; coverage=true)'

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("FEniCS")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("FEniCS")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
